---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
‘Twas brillig, and the slithy toves   
   Did gyre and gimble in the wabe;  
All mimsy were the borogoves,  
   And the mome raths outgrabe.  
“Beware the Jabberwock, my son  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
The grey sea and the long black land;   
And the yellow half-moon large and low;   
And the startled little waves that leap   
In fiery ringlets from their sleep,   
As I gain the cove with pushing prow,   
And quench its speed i' the slushy sand.  
  
Then a mile of warm sea-scented beach;   
Three fields to cross till a farm appears;   
A tap at the pane, the quick sharp scratch   
And blue spurt of a lighted match,   
And a voice less loud, thro' its joys and fears,   
Than the two hearts beating each to each!   
